### ISSUE TITLE
fix to get_scholar_id

### ISSUE THREAD

**Issue by agbarnett** [jkeirstead/scholar#111]
The search pattern in `get_scholar_id` is missing some researchers. For example searching for "Paul Glasziou" gives [this web page](https://scholar.google.com/citations?view_op=search_authors&mauthors=Paul+Glasziou&hl=en&oi=ao). Paul's ID is "7Lh_arwAAAAJ". However, the current search pattern using `;user=[[:alnum:]]+[[:punct:]]` truncates this to "7Lh_" (ending at the punctuation). I think a better search pattern would be `;user=[[:graph:]]{12}` so 12 characters that are either alnum or punct. Looking at a database of around 40 researchers, I can see all their scholar IDs are 12 characters long.

**Comment by GuangchuangYu** [comment]
thanks, see <https://github.com/YuLab-SMU/scholar/commit/29fd4d3ebc89f87d6ef410f56a544da7d6a27fd2>.
