### ISSUE TITLE
Fix for duplicate profiles

### ISSUE THREAD

**Issue by agbarnett** [jkeirstead/scholar#112]
Some people have duplicate profiles with different scholar IDs, so the `get_scholar_id` search function finds multiple matches but then does not return either. Changing the following line will take the first of multiple matches `x_profile <- profiles[[which(which_profile != 0)[1]]]` by adding the `[1]`.

**Comment by GuangchuangYu** [comment]
thanks and incorporated, see <https://github.com/YuLab-SMU/scholar/commit/cbd881c1809901ff6701c79f3c6f02d316351c4a>.
