### ISSUE TITLE
aggregate or group h-index would be great

### ISSUE THREAD

**Issue by Algernon1971** [jkeirstead/scholar#19]
What would be really useful is an addition that allows the calculation of overall lifetime h-index for a group of scholars- such as a lab, a department, and so forth....allow the user to input all ids within the group, and spit out the total number of citations and h-index for the group as a whole. G-index would be a welcome addition to this proposed module or existing ones.

**Comment by jkeirstead** [comment]
I'd like to keep the core package focused on the core data.  This sort of aggregation can be easily achieved with core R tools.
