### ISSUE TITLE
Incomplete author list for publication 

### ISSUE THREAD

**Issue by mqpasta** [jkeirstead/scholar#21]
I observed that Google Scholar do not list all authors if a publication has number of authors more than 5 or 6 ( "..." appear at the end of authors). 

For this, we need to parse publication page instead of profile page for any such specific publication. I wrote a simple code to achieve this. Can you incorporate in package so other people can get benefit? 

getCompleteAuthors = function(id, pubid)
{
  auths = ""
  url_template =  "http://scholar.google.com/citations?view_op=view_citation&citation_for_view=%s:%s"
  url = sprintf(url_template, id, pubid)

  #   print("parsing html")
  tree = htmlTreeParse(url, useInternalNodes = T)
  #   print("finding authors")
  auths   = xpathApply(tree, '//*/div[@class="gsc_value"]',xmlValue)[[1]]

  return(auths)

}

**Comment by jkeirstead** [comment]
That looks very helpful.  I'll incorporate it into the next release - thanks!

**Comment by jefferis** [comment]
Closed as superseded by #51
