### ISSUE TITLE
better error message for bad article ID?

### ISSUE THREAD

**Issue by bbolker** [jkeirstead/scholar#22]
This [StackOverflow question](http://stackoverflow.com/questions/33570390/r-package-scholar-getting-the-citation-history-of-an-article) clearly reflects user error/confusion, but the error message that you get when putting in a bogus article ID,

```
Error in min(years):max(years) : result would be too long a vector
In addition: Warning messages:
1: In min(years) : no non-missing arguments to min; returning Inf
2: In max(years) : no non-missing arguments to max; returning -Inf
```

is not terribly transparent to new users, and could probably be clearer ...

**Comment by jkeirstead** [comment]
Thanks for raising this Ben.  I'll add some checking of the arguments so that a more sensible error is thrown before it tries to create an infinitely long sequence of years!

**Comment by jefferis** [comment]
There is a fix for this in develop.
