### ISSUE TITLE
 Error: is.handle(handle) is not TRUE   in get_profile()  ... and other functions

### ISSUE THREAD

**Issue by mkoehlermsu** [jkeirstead/scholar#24]
Like others, I was having problems with the cookies / 2 requests issues just recently fixed. Was happy to see the new version posted fixing the error. 

With the new version, however, everything I try gives me the following error:
    Error: is.handle(handle) is not TRUE

This includes all the simple examples on the Readme doc, such as the following code:

    # Define the id for Richard Feynman
    id <- 'B7vSqZsAAAAJ'

    # Get his profile and print his name
    l <- get_profile(id)
    l$name 

    # Get his citation history, i.e. citations to his work in a given year 
    get_citation_history(id)

    # Get his publications (a large data frame)
    get_publications(id)

**Comment by jkeirstead** [comment]
I can't reproduce this on my machine.  Can you give me a bit more information, for example, `sessionInfo()`?  Does the `httr` package work as expected for you?

**Comment by mkoehlermsu** [comment]
I see that the new library was created using 3.2 version of R, and I was running 3.1.1.   I upgraded my R to 3.2.2 and re-installed packages, and it works fine now.

Glad it's fixed, sorry for the alarm bells.

Eager to check out this package.
