### ISSUE TITLE
how to find out the author ID given the name

### ISSUE THREAD

**Issue by lalas** [jkeirstead/scholar#28]
Hello,

In  the given example, you have started with an ID for the author. Is there a way to find out the author ID given his/her name?

Thanks

**Comment by Kyeongan** [comment]
It is mentioned in Basic features saying that "http://scholar.google.com/citations?user=B7vSqZsAAAAJ and so his unique id is B7vSqZsAAAAJ."

**Comment by jkeirstead** [comment]
And in the sentence before that, "Individual scholars... can be found by searching for an author and inspecting the resulting scholar homepage."
