### ISSUE TITLE
tidy_id : Error in curl::curl_fetch_memory(url, handle = handle) :    Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by fguilhaumon** [jkeirstead/scholar#32]
Seems the tidy_id function is not working anymore because of the "https" call in the "sample_url" variable.

Replacing "https"  by "http" in the "sample_url" variable solve the issue, however it needs a package recompilation.

**Comment by jefferis** [comment]
I don't think this is a problem any more. @fguilhaumon, please reopen if you disagree. Thanks!
