### ISSUE TITLE
Error retrieving article citation history

### ISSUE THREAD

**Issue by Athanasiamo** [jkeirstead/scholar#33]
Hi.

I love this package! 

But I get errors getting some citation history. I get this very inconsistent error. That is, the error is always the same, but it occurs at differing times (sometimes it will loop through all publications I want without error, other times it will fail at varying papers, i.e. it does not always fail at the same paper!):

Error in if (zero_range(from) || zero_range(to)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In max(as.numeric(cit$year)) :
  no non-missing arguments to max; returning -Inf
2: In max(cit$cites) : no non-missing arguments to max; returning -Inf

trying to get cite data from all of this users publications (not counting the ones that have NA's in them).

I'll try to give you reproducible example (but as I said, it does not always fail!)

    USR="yiSLTAcAAAAJ"

    ### Publications and citation history ####
    Pubs = get_publications(USR)  #get publication information
    Pubs$cites = as.numeric(as.character(Pubs$cites))
    Pubs = Pubs[complete.cases(Pubs),]
    
    Years = seq(from=min(Pubs$year,na.rm=T),to=max(Pubs$year,na.rm=T),by=1)
    CiteYears = as.data.frame(matrix(0, ncol=length(Years), nrow=nrow(Pubs)))
    names(CiteYears) = as.character(Years)
    
    ###Get each article's cite history
    pb = txtProgressBar(min = 1, max = nrow(CiteYears), initial = 1, style=3) ##Set progressbar
    for(i in 1:nrow(CiteYears)){
      setTxtProgressBar(pb,i)
      CitePub = get_article_cite_history(USR,Pubs$pubid[i])
      CitePub = cast(CitePub, value="cites", ~year)[,-1]
      CiteYears[i, grepl(paste(names(CitePub),collapse="|"),names(CiteYears))] = CitePub
    }
    
    Pubs = cbind(Pubs,CiteYears)

**Comment by jkeirstead** [comment]
Google can restrict users if they submit too many queries to Scholar in a short period of time; this is likely to result in `scholar` getting an unexpected result and returning the error you are seeing.  It's hard to know exactly where the thresholds lie and it may vary with load, time of day, etc, hence why you only see it occasionally.

One possibile fix would be to add a delay into your `for` loop, something like:

```
for (i in 1:nrow(CiteYear)) {
    ...
    # Add an arbitrary 10 second delay every 20 rows
    if (i %% 20 == 0)  Sys.sleep(10) 
}
```
You might need to play around with the exact timing of the delay but it should help you get past any throttling restrictions.  Though of course, your code will take longer to run!

**Comment by Athanasiamo** [comment]
ah, yes! Of course, I should have thought of google restrictions like that. That did the trick!
