### ISSUE TITLE
Cannot get `pubid` after Google Scholar redesign

### ISSUE THREAD

**Issue by rudazhan** [jkeirstead/scholar#38]
Google Scholar changed its design recently and `pubid` return by `scholar::get_publications()` are now "void(0)".

**Comment by rudazhan** [comment]
The HTML node matched for `title` and `pubid` now look something like this:
```html
<a href="javascript:void(0)"
data-href="/citations?view_op=view_citation&amp;hl=en&amp;user=8udO65kAAAAJ&amp;citation_for_view=8udO65kAAAAJ:u-x6o8ySG0sC"
class="gsc_a_at">Not so different after all: A cross-discipline view of trust</a>
```
Notice `href` does not contain anything, but `pubid` is within `data-href` under key `citation_for_view` (formatted as "user:pubid").

**Comment by jkeirstead** [comment]
Unfortunately I'm no longer maintaining this package (see 512dae95d281eb1d39972c5e737bafcba53731a2).  Please feel free to incorporate this change on a fork.

**Comment by rudazhan** [comment]
Alright. I'll let you know when I get time to fork and fix this.
