### ISSUE TITLE
Prepare for scholar 0.1.6

### ISSUE THREAD

**Issue by jefferis** [jkeirstead/scholar#43]
- [x] Switch maintainer in DESCRIPTION
- [x] Remove missing maintainer note in README
- [x] merge develop to master and bump version in DESCRIPTION
- [x] tag and prepare github release
- [x] release to CRAN

Additionally
- [x] travis?
- [ ] add rstudio project?

@GuangchuangYu are you OK to review develop and take this the next step?

**Comment by jefferis** [comment]
@GuangchuangYu Because I mistakenly merged your PR #39 to master rather than develop and it updated the NEWS / Version, there is now a conflict between the two. I hope it is not too inelegant but I have cherry picked your PR to develop and resolved the conflict in a way that seems correct to me.

**Comment by jefferis** [comment]
So now you should just be able to make any changes you like on develop and then merge into master preferring the changes in develop where this a conflict.

**Comment by GuangchuangYu** [comment]
did you push your changes? 

Still showing conflict on my local clone.

**Comment by jefferis** [comment]
I did not merge develop into master. The cherry pick doesn't resolve the conflict unfortunately (because it is in a branch that has not been merged). I guess I will be more careful in future to check that a PR is against develop, which has been James' style until now.

**Comment by GuangchuangYu** [comment]
OK. I have merged master to develop branch. Now we can use develop for preparing 0.1.6 and merge it to master when it is ready.

**Comment by GuangchuangYu** [comment]
- [x] vignette added.

```r
## open the vignette
vignette("scholar", package="scholar")
```

**Comment by jefferis** [comment]
I've reviewed the vignette and pushed a few minor changes. Looks good to me - nice work! I would be ready to release now. To target an ropensci release, we would additionally need to add examples for all functions in their individual help.

**Comment by GuangchuangYu** [comment]
Yes, we need to move forward to release to CRAN first. Since the old version can't work properly, we need to update it asap.

After that, we can add examples and submit to ropensci. rOpenSci reviewers also need times to review the pkg and we also need times to address their comments.

**Comment by GuangchuangYu** [comment]
- [x] merge develop to master and bump version in DESCRIPTION
- [x] tag and prepare github release
- [ ] release to CRAN

Now it is ready to release to CRAN. I think @jkeirstead should be the one to submit to CRAN this time.

**Comment by GuangchuangYu** [comment]
One more thing:

```
✔  checking installed files from ‘inst/doc’
✔  checking files in ‘vignettes’
N  checking examples
   Examples with CPU or elapsed time > 5s
                            user system elapsed
   compare_scholar_careers 0.408  0.014   5.098
✔  checking for unstated dependencies in vignettes
✔  checking package vignettes in ‘inst/doc’
✔  checking re-building of vignette outputs
```

The examples are too slow, as Feynman and Stephen Hawking have so many pages of paper records to retrieve. 

We may need to using other scholars to speed up the package compilation.

**Comment by jefferis** [comment]
Some of the examples use Isaac Newton – I think we should not use him as the compare_scholar functions are treating works from 1980-present as if they represent his career. I have changed them to Stephen Hawking like the vignette. 

We can mark any examples that take too long as `donttest`

One other thing, we should prob agree a white space default – James was using 4 spaces for tabs. I think your editor adds tabs.

**Comment by GuangchuangYu** [comment]
I think I did use 4 spaces for tabs.

The updated example was merged to master.

**Comment by jefferis** [comment]
Super!

**Comment by mdingemanse** [comment]
Sorry to butt in, but regarding the Hawking/Feynman comparison in @jefferis 's comment, I was wondering whether this new release still has the problem I [reported](https://github.com/jkeirstead/scholar/issues/37) for the previous version, which is that the output seems to be capped at the most recent 8 years (instead of whole career).

**Comment by jefferis** [comment]
Just a note that #37 was fixed and scholar has been on cran for a while, so i think we can close.
