### ISSUE TITLE
Get URL or DOI

### ISSUE THREAD

**Issue by DominiqueMakowski** [jkeirstead/scholar#45]
Would it be possible that  `scholar::get_publications()` also find DOI / URL ? That would very useful!

Thanks for that package!

**Comment by jefferis** [comment]
PR is welcome if you have an idea, even partial. My impression is that you would need to follow the scholar link for each publication in order to get the external URL.

**Comment by DominiqueMakowski** [comment]
Sorry but I have no skills whatsoever regarding web scrapping 😕 I just hope somebody will crack it
