### ISSUE TITLE
get_publications only works once

### ISSUE THREAD

**Issue by mkgrace** [jkeirstead/scholar#47]
Hello, I am trying to pull publications for multiple authors. However, get_publications() only works the with the first ID it is used on in a session- if I try to use it with a subsequent ID, the following is returned:

[1] title   author  journal number  cites   year    cid     pubid  
<0 rows> (or 0-length row.names)

Any thoughts? I've carefully checked the IDs, and they are valid and all work- as long as they are the first one tried in a particular session. To do another one, I have to end the session and reopen R, which is very inefficient!

**Comment by rudazhan** [comment]
That's very strange. I do not see such issue on my computer. Can you make sure your R and scholar are up to date?

**Comment by mkgrace** [comment]
@rudazhan That was my first line of thinking, but even with the latest versions the problem persists. With some more experimenting, it seems like it could be related to memory- if I remove all objects (except for the array I'm writing to) after running get_publications(), it will work for up to 8 IDs and then the same problem happens.

**Comment by rudazhan** [comment]
That is indeed very unusual. I have never seen this kind of issue before. Can you post your code with the entire outputs? Make sure you run from a new R session.

**Comment by rudazhan** [comment]
Start a new R session, try the following:
```R
remove.packages("scholar")
devtools::install_github("jkeirstead/scholar")
```
This should get you the development version of `scholar`. The latest release is v0.1.6.
Let me know if the problem still exists.

**Comment by cicekguven** [comment]
I am having a similar issue, get_publications returns an empty table. Yesterday It was working. I do not know if there is a limit on the number of queries that one can do on google scholar. I tried the solution suggested above, and the problem is still there. Yesterday the function was working.

**Comment by rudazhan** [comment]
My experience with Google Scholar is that they may block your access if you send too many requests in a short period of time. This may or may not be the issue you are experiencing.

**Comment by jefferis** [comment]
Closing this old issue v likely due to rate limiting.
