### ISSUE TITLE
error for get_article_city_history

### ISSUE THREAD

**Issue by StefanLindow** [jkeirstead/scholar#48]
I extracted the publication list from one author and tried to get the article citation history though with an error message. The article tried here is from 2012 and has 86 citations. Not that much to crash a function. 

> article1 <- get_article_cite_history('fYQY8Y8AAAAJ', '7591188124196201684')
`Error in min(years):max(years) : result would be too long a vector
In addition: Warning messages:
1: In min(years) : no non-missing arguments to min; returning Inf
2: In max(years) : no non-missing arguments to max; returning -Inf`

**Comment by rudazhan** [comment]
Use `pubid` instead, e.g. `article1 <- get_article_cite_history('fYQY8Y8AAAAJ', 'd1gkVwhDpl0C')`

**Comment by StefanLindow** [comment]
thanks!
1) did try that. same error message.
2) Where did you get the pubid from? When I scrap the publications through get_publications() I only get the cid, not the pubid (the whole column shows: "void()" )

**Comment by StefanLindow** [comment]
and let me add the following: Can I scrape the citation history of a publication not affiliated with an account?

**Comment by rudazhan** [comment]
I get `pubid` from `scholar::get_publications()`, which returns a data.frame with columns:
> "title"   "author"  "journal" "number"  "cites"   "year"    "cid"     "pubid"

**Comment by sbalci** [comment]
with `scholar::get_publications()` the pubid column is only consisting of "void(0)"

**Comment by sbalci** [comment]
Thank you, it works with development version v0.1.6
Best wishes.

**Comment by rudazhan** [comment]
You're welcome.

**Comment by StefanLindow** [comment]
yap, thank you!

**Comment by rudazhan** [comment]
@StefanLindow Please close this issue if problem has been solved.
