### ISSUE TITLE
get_oldest_article() returns Inf when article does not have year

### ISSUE THREAD

**Issue by sbalci** [jkeirstead/scholar#50]
`get_oldest_article()` returns `Inf` when some articles do not have year.

like in this profile:  `get_oldest_article("QW5aIMgAAAAJ")`

I would like to get multiple authors' information using `purrr:map(ids, get_oldest_article)` and the function stops due to `Inf` result.
Is it possible to return `NA` or "smallest year available" ?

Best wishes

**Comment by GuangchuangYu** [comment]
```
> require(scholar)
Loading required package: scholar
> get_oldest_article("QW5aIMgAAAAJ")
[1] 1990
> packageVersion('scholar')
[1] ‘0.1.6’
```

**Comment by sbalci** [comment]
My package is updated. This is what I get. The error is in Turkish. says: "no missing argument for min, returns Inf"

```
> require(scholar)
> get_oldest_article("QW5aIMgAAAAJ")
[1] Inf
Warning message:
In min(papers$year, na.rm = TRUE) :
  min için eksik olmayan argüman yok; Inf döndürülüyor
> packageVersion('scholar')
[1] ‘0.1.6’
```

**Comment by mkiang** [comment]
Pretty sure this issue should be closed. `get_oldest_article()` is literally just using `min(..., na.rm = TRUE)` and the error cannot be reproduced.

**Comment by sbalci** [comment]
I have tried now. You are right. I cannot reproduce it either. Thank you :)
