### ISSUE TITLE
Integrating function from `coauthornetwork` package.

### ISSUE THREAD

**Issue by cimentadaj** [jkeirstead/scholar#53]
Hi! Thanks a lot for `scholar`, it's a very interesting package. Inadvertently, I created the `coauthornetwork` package which does a very simple thing: extracts your coauthor network and visualizes a network of coauthorship. 

Of course the package would be much better if it used the already existing functions from the `scholar` package. Would you be open to integrating the function from `coauthornetwork` in `scholar`? @mkiang suggested the idead [here](https://twitter.com/mathewkiang/status/1009174941110099969) and it made sense to me as this is purely a two-function package which will be probably fit much better using the already existing structure of `scholar`.

I'd adapt the code to match the style/dependencies of the package, of course.

You can check out the package [here](https://github.com/cimentadaj/coauthornetwork).

**Comment by GuangchuangYu** [comment]
This is a neat feature. PR is welcome!
