### ISSUE TITLE
Get citation history for a single article

### ISSUE THREAD

**Issue by jkeirstead** [jkeirstead/scholar#6]
In addition to giving citation histories for an author, you can also view the [results for a single article](http://scholar.google.com/citations?view_op=view_citation&hl=en&user=ZNt03WkAAAAJ&citation_for_view=ZNt03WkAAAAJ:u-x6o8ySG0sC).  It would be nice to able to retrieve these values as well.

**Comment by mkiang** [comment]
Something like this would work in most cases:

```
get_article_cite_history <- function (id, article) {
    id <- tidy_id(id)
    url_base <- paste0("http://scholar.google.com/citations?", 
                       "view_op=view_citation&hl=en&citation_for_view=")
    url_tail <- paste(id, article, sep=":")
    url <- paste0(url_base, url_tail)
    doc <- htmlTreeParse(url, useInternalNodes = TRUE)
    years <- as.numeric(xpathSApply(doc, "//*/span[@class='gsc_g_t']", 
                                    xmlValue))
    vals <- as.numeric(xpathSApply(doc, "//*/span[@class='gsc_g_al']", 
                                   xmlValue))
    df <- data.frame(year = years, cites = vals)
    df$pubid <- article
    return(df)
}
```

However, it runs into problems if the article has any years with 0 citations (i.e., number of elements in `years` and in `vals` will not be the same so the `data.frame()` will throw up an error.

**Comment by mkiang** [comment]
Also, just as an example, `get_article_cite_history("eD9_J3wAAAAJ", "9yKSN-GCB0IC")`
will throw up an error (2012 has 0 citations). Meanwhile, `get_article_cite_history("eD9_J3wAAAAJ", "d1gkVwhDpl0C")` works just fine.

**Comment by jkeirstead** [comment]
Thanks for the code @mkiang.  I've now implemented this in a10e47944df810cf3de5a1a9252a54b2dda4b33b including a fix for the 0 citation issue you mention.

**Comment by lizziengo** [comment]
Is there any way I can get the publication history of a single article without a user id?

**Comment by jefferis** [comment]
Unfortunately I don't think there is. Even the simpler question of the total number of citations for a paper where there is no user id does not seem to have a very good solution (see #74).

**Comment by lnalborczyk** [comment]
Hi, thank you for developing and maintaining the package!

It seems that get_article_cite_history(id, article) currently reports the number of citations per year. But is there a way of getting the IDs of articles citing the original "article"?
