### ISSUE TITLE
Shiny Error

### ISSUE THREAD

**Issue by qowjdwns3** [jkeirstead/scholar#72]
Hi,

I've been trying to publish a Shiny app using Scholar package to my dashboard, but kept getting this error message: "Error in get_resp: Cannot connect to Google Scholar." It seems like the package fails to grab the information on the web. Could anybody give me some clarification on this issue?

**Comment by alegione** [comment]
Also found this same issue, works locally but once published it fails

**Comment by jefferis** [comment]
Likely to do with Google rate limiting connections from your host. If you look around there are quite a few issues here that boil down to the fact that Google is not encouraging people to query scholar as an API.
