### ISSUE TITLE
vector of pubids in get_article_cite_history()

### ISSUE THREAD

**Issue by jotech** [jkeirstead/scholar#75]
I would like to check the citation per year for several articles. However calling the function ``get_article_cite_history`` is taking some time. I'm just wondering if it would be faster to allow also a vector of pubids and do one google database request for all pubids at once?
```R
get_article_cite_history(id, c("Tyk-4Ss8FVUC", "u-x6o8ySG0sC"))
Error in request(method = y$method %||% x$method, url = y$url %||% x$url,  : 
  length(url) == 1 is not TRUE
```

**Comment by jefferis** [comment]
Thanks for the suggestion. Unfortunately retrieving the information for each article is a separate web page request i.e. it is not possible to do in one go.
