### ISSUE TITLE
get_article_cite_history is not working properly

### ISSUE THREAD

**Issue by AustinDavidRichards** [jkeirstead/scholar#81]
Could there be a bug from a recent R update? Consider the following, which returns an empty dataframe with the correct column headers:

```{r}
library(tidyverse)
library(scholar)

id <- '0853ilkAAAAJ&hl'

all_pubs <- get_publications(id)

all_pubs$title

all_pubs %>% 
  filter(title == "Data-driven asthma endotypes defined from blood biomarker and gene expression data") %>% 
  select (pubid) #returns M05iB0D1s5AC


article <- 'M05iB0D1s5AC'

humpf <- get_article_cite_history(id, article)
```

Or more simply:
```{r}
df<- get_article_cite_history("0853ilkAAAAJ&hl", "M05iB0D1s5AC")
```

**Comment by jefferis** [comment]
Can you check that id? There is an “&hl” at the end that looks odd.

**Comment by AustinDavidRichards** [comment]
So I believe the ID is correct as 'get publications' works with it as expected, thanks!

**Comment by AustinDavidRichards** [comment]
I may have misspoke, removing the '&hl' still works for 'get_publications', but now loads several entreis for 'get_article_cite_history', (though oddly only 5 rather than the ~25 or so expected) thanks!!!
