### ISSUE TITLE
Publication limit at 100

### ISSUE THREAD

**Issue by tombroekel** [jkeirstead/scholar#83]
It seems impossible to get all publications of authors with more than 100 publications, as the parameter "pagesize" does not seem to work.

**Comment by Vaufreyd** [comment]
Hello,

You may find a suitable solution here https://www.r-bloggers.com/yet-another-post-on-google-scholar-data-analysis/ with the get_all_publications function.

Doms.

**Comment by jefferis** [comment]
> It seems impossible to get all publications of authors with more than 100 publications

@tombroekel this is (not / no longer) true.

For example [Liqun Luo has 308 publications at the time of writing](https://scholar.google.com/citations?user=1X-MOE8AAAAJ&hl=en&oi=ao) and you can get them all like so:
```
> pubs=get_publications('1X-MOE8AAAAJ')
> nrow(pubs)
[1] 308
```
The `pagesize` argument controls the size of the batches in which publications are downloaded not the total number of publications that can be retrieved. I have updated the docs to clarify this in c935ea7. If you feel that this doesn't address your original issue then please re-open with a reproducible example.
