### ISSUE TITLE
get_complete_authors - Error 429 (rate limiting)

### ISSUE THREAD

**Issue by JConigrave** [jkeirstead/scholar#84]
The get_complete_authors function works effectively, but may smash google servers.
It scrapes a different page to get author lists for each pub.

As this function is not vectorized, naiive users (me) may try and include it in a lapply without any speed breaks i.e. Sys.sleep(). Frequent accessing of google scholar pages risks user IP ranges being flagged as likely bots and violating terms of service. This may cause 429 errors and could shut down the functionality of the entire scholar package. For me it's been over 12 hours and I'm still locked out.

I think this function either needs clear warnings, needs to be vectorized safely, or perhaps should not be exported to the general user base.

**Comment by GuangchuangYu** [comment]
I think @abfleishman may help on this issue.

**Comment by abfleishman** [comment]
@JConigrave I am sorry that you were locked out!  That is a major bummer.  Honestly, I am a novice when it comes to anything with scraping the web.  As I mentioned in the pull request making the function, I did not test it extensively or try to break it. We would love it if you wanted to take a stab at vectorizing safely?

**Comment by JConigrave** [comment]
@abfleishman no worries, google let me out of jail about 24 hours later. The function still solved my problem so very grateful for your work! Happy to take a crack at this one. I'll make a fork.

**Comment by abfleishman** [comment]
@JConigrave as far as I can tell this package is maintained by @GuangchuangYu but also really the community of users and with the original developer no longer involved much.
