### ISSUE TITLE
"Sort by Title" (and similar) listed as coauthors!

### ISSUE THREAD

**Issue by agmunozs** [jkeirstead/scholar#86]
Issue as indicated in the title.

Way to reproduce it: run this code...

################################################
closeAllConnections()
rm(list=ls())
library(scholar)
my_id <- '_Q2Gh20AAAAJ'
l <- get_profile(my_id)
cit <- get_citation_history(my_id)
coauthor_network <- get_coauthors(my_id, n_coauthors = 6, n_deep = 1)
plot_coauthors(coauthor_network)

At least two coauthors are pointing at "Sort by X", rather than an actual name.

**Comment by agmunozs** [comment]
No news? :(

**Comment by jefferis** [comment]
Thanks @agmunozs was closed by e9422bd7d333df36cee8110b116e5ab09e89a33d
