### ISSUE TITLE
Add function to flush the cache

### ISSUE THREAD

**Issue by jkeirstead** [jkeirstead/scholar#9]
Caching is used to avoid hammering Google's servers when making multiple requests for a scholar's data.  However it would be useful to have an option to flush the cache, at least for development.

**Comment by jefferis** [comment]
A note here, in case anyone feels like implementing. The cache is implemented on top of the R.cache package. R.cache uses a single, shared cache location for all memoised calls. Thus blasting the cache location would remove data from any other activities from within the current R session that use `R.cache`. It seems that it might be nice if R.cache were able to store data to a specific location according to the package that invokes it.

**Comment by jkeirstead** [comment]
Implemented with b1a63f17648a26bf06ddc76f38a84c19daf0556e.  

@jefferis, I've coded this so that only the cached object for the specified ID is cleared.  I've also added a separate directory for `r-scholar` in the temp directory to keep things tidy.
