### ISSUE TITLE
Invalid UTF-8 error when trying to retrieve author names with accents

### ISSUE THREAD

**Issue by mkiang** [jkeirstead/scholar#92]
When trying to get complete authors for an article that contains author names with accents, I get an encoding error. This error didn't happen as of December 2020. (I.e., it may be a result of the recent UI changes?)

Below is a concrete reproducible example. This happens in both macOS and Linux.

```
> scholar::get_complete_authors("eD9_J3wAAAAJ", "pQTOvowfQioC")
Error in sub(re, "", x, perl = TRUE) : input string 5 is invalid UTF-8
```

**Comment by mkiang** [comment]
NOTE: I ended up modifying the above reference in my Scholar page to remove the accent so it now longer throws an error. The bug, however, still exists and any article with author names that have accents will throw a UTF-8 error.

**Comment by jefferis** [comment]
Thanks for the issue @mkiang. Can you point to another example of this error?

**Comment by mkiang** [comment]
Weird, I don't get it anymore. Apologies — must have been fixed in one of the packages after I updated. For future reference, this code used to give me an error:

```
scholar::get_complete_authors("G5ACIwoAAAAJ", "ZeXyd9-uunAC")
```

I'll close now.

**Comment by jefferis** [comment]
Thanks!
