### ISSUE TITLE
Retrieving field-of-interest/expertise labels

### ISSUE THREAD

**Issue by TS404** [jkeirstead/scholar#94]
Is there any way that `get_profile(id)` could be expanded to also retrieve the field-of-interest/expertise labels that profile holders assign to themselves?

**Comment by TS404** [comment]
I've found a way of doing this! See pull request #95

**Comment by jefferis** [comment]
Thanks again for PR.

**Comment by TS404** [comment]
I've made a few additional updates to the `get_profile(id)` function to handle the new way of handing fields of expertise, and to return available/not_available numbers of publications (pull request #104).
I think I've correctly updated the necessary .R function file and .Rd manual file (no changes should be needed to the namespace this time).
