### ISSUE TITLE
get_publications(id) is not returning pubid 

### ISSUE THREAD

**Issue by Ruheyan** [jkeirstead/scholar#96]
When I run the following code, the "pubid" suppose to show publication ids, but now it is all returning NA.
`id <- 'B7vSqZsAAAAJ'`
`get_publications(id)`

Is there any way to sort this out please? Many thanks!

**Comment by conig** [comment]
This should now be fixed if you update to the latest version on github:
```
# remotes::install_github("jkeirstead/scholar")

id <- 'B7vSqZsAAAAJ'
scholar::get_publications(id)$pubid[1:5]
#> [1] "hMod-77fHWUC" "u-x6o8ySG0sC" "SP6oXDckpogC" "2P1L_qKh6hAC" "d1gkVwhDpl0C"
```

**Comment by Ruheyan** [comment]
Many thanks, it is now working well.

**Comment by GuangchuangYu** [comment]
now on cran.
