### ISSUE TITLE
get_article_cite_history(id, pubid) sometimes is not returning 

### ISSUE THREAD

**Issue by Ruheyan** [jkeirstead/scholar#99]
get_article_cite_history ( ) is not returning as expected sometimes. For example, if I run 

`id <- "B7vSqZsAAAAJ" `
`pubid <- get_publications(id)$pubid `
`get_article_cite_history(id,pubid_test[30])`

reports error as follow: 
_Error in data.frame(year = years, cites = vals) : 
  arguments imply differing number of rows: 24, 23_

I guess it is because this paper was not cited immediately(same year/the second year) after publication. Is there any way to sort it out?

Many thanks

**Comment by jefferis** [comment]
Many thanks. You're quite right. This was a consequence of the change in 13fa644de7a3747aaced7f406505bedd6228648d that was designed to catch up with changes in how Google present data. I had forgotten that it is necessary to extract the years from the code from the bars. Related to dd59a23 and 6562f1a.

**Comment by Ruheyan** [comment]
Sorry, get_article_cite_history ( ) is still not working. Do you have any suggestions on what I need to do?

**Comment by jefferis** [comment]
Restart R and reinstall scholar.
```
> remotes::install_github('jkeirstead/scholar')
> library(scholar)
> id <- "B7vSqZsAAAAJ"
> pubid <- get_publications(id)$pubid
> get_article_cite_history(id,pubid[30])
   year cites        pubid
1  1998     4 qxL8FJ1GzNcC
2  1999     0 qxL8FJ1GzNcC
3  2000     8 qxL8FJ1GzNcC
4  2001    13 qxL8FJ1GzNcC
5  2002    23 qxL8FJ1GzNcC
6  2003    28 qxL8FJ1GzNcC
7  2004    64 qxL8FJ1GzNcC
8  2005    21 qxL8FJ1GzNcC
9  2006    38 qxL8FJ1GzNcC
10 2007    37 qxL8FJ1GzNcC
11 2008    36 qxL8FJ1GzNcC
12 2009    53 qxL8FJ1GzNcC
13 2010    45 qxL8FJ1GzNcC
14 2011    39 qxL8FJ1GzNcC
15 2012    39 qxL8FJ1GzNcC
16 2013    44 qxL8FJ1GzNcC
17 2014    32 qxL8FJ1GzNcC
18 2015    48 qxL8FJ1GzNcC
19 2016    39 qxL8FJ1GzNcC
20 2017    35 qxL8FJ1GzNcC
21 2018    50 qxL8FJ1GzNcC
22 2019    36 qxL8FJ1GzNcC
23 2020    41 qxL8FJ1GzNcC
24 2021     9 qxL8FJ1GzNcC
```
